// apps/solid_docs/.storybook/preview.tsx
import { JSX } from 'solid-js';
import type { Preview } from 'storybook-solidjs-vite';
import { MantineProvider } from '@mantine/core';

const preview: Preview = {
  parameters: {
    // automatically create action args for all props that start with "on"
    actions: { argTypesRegex: '^on.*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    (Story: () => JSX.Element) => (
      <MantineProvider>
        <Story />
      </MantineProvider>
    ),
  ]
};

export default preview;

// apps/docs/.storybook/preview.tsx
import React from 'react';
import type { Preview } from 'storybook-solidjs';
import { MantineProvider } from "@mantine/core";
// import { theme } from './theme';

const preview: Preview = {
  decorators: [
    (renderStory) => (
      <MantineProvider theme={{}}>
        {renderStory()}
      </MantineProvider>
    ),
  ],
  parameters: {
    layout: 'fullscreen',
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
